<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\ConfigurableProduct\Block\Product\View\Type\Configurable;
use Magento\Framework\Escaper;

/** @var Configurable $block */
/** @var Escaper $escaper */

$product = $block->getProduct();
$productId = $product->getId();

?>


<script>
    window.addEventListener("update-prices-" + <?php echo $productId; ?>, function(event) {
        if(finalPrice = event?.detail?.finalPrice?.amount) {
            let meta = document.querySelector('meta[property="product:price:amount"]');
            meta && meta.setAttribute('content', finalPrice);
        }
    }, false);
</script>
